### ISSUE TITLE
Compatibility with FernFlower?

### ISSUE THREAD

**Issue by Jonatino** [deathmarine/Luyten#38]
Was wondering if compatibility with FernFlower could be added to this GUI. 

EDIT: I noticed that you said Luyten's predecessor used fernflower. Could you send me a link to it so I can try it out please?

**Comment by deathmarine** [comment]
That version of Luyten was a test and was inefficient because it relied on reading the output stream from the command line, decompilng and caching the entire jar. Fernflower at that time was obfuscated and I didn't have the time to call functions inside the software so I used the command line to write all the output files.

However, now that the source is open and view-able within IntelliJ I've considered it however haven't fitted the software to use anything other than Luyten. Im sure it can be easily retrofitted.
