### ISSUE TITLE
Duplicate Filename Exception when saving sources.

### ISSUE THREAD

**Issue by OfficialAName** [deathmarine/Luyten#56]
Whenever i try to decompile Shiginima Launcher SE v3.100.jar, it gets stuck at 72% then it throws that error!

`java.util.zip.ZipException: duplicate entry: javax/annotation/CheckForNull.java`

Tried to decompile on linux, no luck, tried on windows, no luck..

**Comment by deathmarine** [comment]
Decompile or save all the sources? I've downloaded the same file and its view-able. I'm pretty sure the exception is thrown because the source (*.java) is included in the megajar. It seems they are using maven shade to reduce dependencies but not removing the source files. Either way I can gracefully handle the exception but I never actually anticipate having the sources stored in the jar.

**Comment by OfficialAName** [comment]
ok, thanks for fixing it! could you also post a download link with the fixed one pls >?

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/releases/tag/v0.4.9
